"""add_host_token_hash_column

Revision ID: 08f045a62d76
Revises: 716c363394f8
Create Date: 2026-02-09 16:16:32.138299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f045a62d76'
down_revision: Union[str, None] = '716c363394f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('host_token_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'host_token_hash')
    # ### end Alembic commands ###
