"""add_discounts_table

Revision ID: 716c363394f8
Revises: 291dc60acb7f
Create Date: 2026-02-07 17:31:13.243882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716c363394f8'
down_revision: Union[str, None] = '291dc60acb7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('session_id', sa.CHAR(length=36), nullable=False),
    sa.Column('participant_id', sa.CHAR(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED', name='discounttype'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discounts')
    # ### end Alembic commands ###
